In [92]:
import csv
data_r=[]
data_c=[]
data_h=[]
label_list=[]
with open('intern_data.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        #print(row['a'], row['b'],row['c'],row['d'])
        
        data_r.append([float(row['a']), float(row['b']),float(row['d']),float(row['e']),float(row['f']),float(row['g'])])
        data_c.append(row['c'])
        data_h.append(row['h'])
        label_list.append(float(row['y']))
print(data_r[:2])
print(data_c[:1])
print(data_h[:1])
print(label_list[:1])

[[0.951785695971921, 0.669569988269359, 0.170130254933611, 0.623469153884798, 0.925886165117845, 0.81268464284949], [0.51044699898921, 0.922627209918573, 0.0878990164492279, 0.0254153392743319, 0.698443632107228, 0.658544838894159]]
['green']
['white']
[3.70751388051659]


In [86]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

values_c = array(data_c)
print('-'*100)
print('Hot encoding C attribute')
print('-'*100)
print('-'*100)
print(values_c[:10])
# integer encode
label_encoder = LabelEncoder()
integer_encoded_c = label_encoder.fit_transform(values_c)
print(integer_encoded_c[:10])
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)

#chaging the shape to a single column from row
integer_encoded_c = integer_encoded.reshape(len(integer_encoded_c), 1)

onehot_encoded_c = onehot_encoder.fit_transform(integer_encoded_c)
print(onehot_encoded_c[:10])
#inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
#print(inverted)

print('-'*100)


values_h = array(data_h)
print('-'*100)
print('Hot encoding H attribute')
print('-'*100)
print('-'*100)
print(values_h[:10])
# integer encode
label_encoder = LabelEncoder()
integer_encoded_h = label_encoder.fit_transform(values_h)
print(integer_encoded_h[:10])
# binary encode

#chaging the shape to a single column from row
integer_encoded_h = integer_encoded_h.reshape(len(integer_encoded_h), 1)
onehot_encoded_h = onehot_encoder.fit_transform(integer_encoded_h)
print(onehot_encoded_h[:10])
#inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
#print(inverted)

print('-'*100)


----------------------------------------------------------------------------------------------------
Hot encoding C attribute
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
['green' 'red' 'yellow' 'green' 'red' 'blue' 'yellow' 'green' 'green'
 'green']
[1 2 3 1 2 0 3 1 1 1]
[[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]]
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Hot encoding H attribute
----------------------------------------------------------------------------------------------------
---------------------------------------------------

In [138]:
import numpy as np
data_arr=np.array(data_r)
#print(data_arr[:2])

data = np.concatenate((data_arr,onehot_encoded_c, onehot_encoded_h), axis=1)
print('Data:')
print(data[:2])
label=np.array(label_list)
print('Label:')
print(label[:2])

Data:
[[ 0.9517857   0.66956999  0.17013025  0.62346915  0.92588617  0.81268464
   0.          1.          0.          0.          0.          1.        ]
 [ 0.510447    0.92262721  0.08789902  0.02541534  0.69844363  0.65854484
   0.          0.          1.          0.          0.          1.        ]]
Label:
[ 3.70751388  2.68924256]


# Linear Regression

In [172]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score


regr = linear_model.LinearRegression()


# Train the model using the training sets
regr.fit(data, label)

# Make predictions using the testing set
pred = regr.predict(data)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(label, pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(label, pred))

print('-'*100)
print('error = label-pred')
error= label-pred
print('max:',error.max())
print('min:',error.min())


Coefficients: 
 [-0.00730915  0.39185073  0.00132106  0.95165108  0.67181686  0.60326591
 -0.58650175  0.31616989 -0.02141574  0.2917476  -0.31682548  0.31682548]
Mean squared error: 0.01
Variance score: 0.97
----------------------------------------------------------------------------------------------------
error = label-pred
max: 0.274337165622
min: -0.324984624686


# Ridge Regression

In [171]:
from sklearn.linear_model import Ridge
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

regr = Ridge(alpha=0.1)
# Train the model using the training sets
regr.fit(data, label)

# Make predictions using the testing set
pred = regr.predict(data)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(label, pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(label, pred))

print('-'*100)
print('error = label-pred')
error= label-pred
print('max:',error.max())
print('min:',error.min())

Coefficients: 
 [-0.0071977   0.39082084  0.00126427  0.94890552  0.67007086  0.60196517
 -0.58591719  0.31587259 -0.02151798  0.29156258 -0.31669966  0.31669966]
Mean squared error: 0.01
Variance score: 0.97
----------------------------------------------------------------------------------------------------
error = label-pred
max: 0.272378207022
min: -0.324424425406


# Polynomial Features

In [202]:
import numpy as np

from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

for degree in [0,1,2, 3, 4, 5,6,7]:
    model = make_pipeline(PolynomialFeatures(degree,include_bias=True), Ridge(alpha=0.1))
    model.fit(data, label)
    pred = model.predict(data)
    # The mean squared error
    print('-'*200)
    print("Mean squared error: %.2f"
          % mean_squared_error(label, pred))
    # Explained variance score: 1 is perfect prediction
    print('Variance score: %.2f' % r2_score(label, pred))
    print('error = label-pred')
    error= label-pred
    print('max:',error.max())
    print('min:',error.min())

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Mean squared error: 0.35
Variance score: 0.00
error = label-pred
max: 1.29770659078
min: -1.70142661735
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Mean squared error: 0.01
Variance score: 0.97
error = label-pred
max: 0.272378207022
min: -0.324424425406
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Mean squared error: 0.01
Variance score: 0.97
error = label-pred
max: 0.219941906371
min: -0.317582420906
---------------------------------------------------------------------------------

# Ridge regression: with Test DataSet and CV
### Cross Validation on training dataset


In [205]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import RidgeCV 

# 30% of the data for the Test is kept at random
X_train, X_test, y_train, y_test = train_test_split(
    data, label, test_size=0.25, random_state=0)


from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score


for degree in [1, 2, 3, 4, 5]:
    print('-'*200)
    print('degree:',degree)
    model = make_pipeline(PolynomialFeatures(degree,include_bias=True), RidgeCV(alphas=[0.001,0.01,0.1,1,10,100],fit_intercept=True,cv=4))
    scores = cross_val_score(model, X_train, y_train, cv=4)
    print('Scores:',scores)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    # The mean squared error
    print("Mean squared error: %.2f"
          % mean_squared_error(y_test, pred))
    # Explained variance score: 1 is perfect prediction
    print('Variance score: %.2f' % r2_score(y_test, pred))
    print('y_test:',y_test[:5])
    print('pred:  ',pred[:5])

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
degree: 1
Scores: [ 0.96934026  0.96531253  0.96973964  0.97079496]
Mean squared error: 0.01
Variance score: 0.97
y_test: [ 2.85508529  2.94973971  2.75635373  1.96371667  3.3201863 ]
pred:   [ 2.90649916  2.95732474  2.75024203  2.07445605  3.22967906]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
degree: 2
Scores: [ 0.96320491  0.95784519  0.96126743  0.95571397]
Mean squared error: 0.01
Variance score: 0.97
y_test: [ 2.85508529  2.94973971  2.75635373  1.96371667  3.3201863 ]
pred:   [ 2.95985861  2.94427767  2.75723716  2.12278776  3.17373051]
------------------------------------------------------------------------------------------

In [215]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LassoCV 

# 30% of the data for the Test is kept at random
X_train, X_test, y_train, y_test = train_test_split(
    data, label, test_size=0.3, random_state=0)

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score


for degree in [1, 2, 3, 4, 5]:
    print('-'*200)
    print('degree:',degree)
    model = make_pipeline(PolynomialFeatures(degree,include_bias=True), LassoCV(alphas=[0.001,0.01,0.1,1,10,100],fit_intercept=True,cv=4))
    scores = cross_val_score(model, X_train, y_train, cv=4)
    print('Scores:',scores)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    # The mean squared error
    print("Mean squared error: %.2f"
          % mean_squared_error(y_test, pred))
    # Explained variance score: 1 is perfect prediction
    print('Variance score: %.2f' % r2_score(y_test, pred))
    print('y_test:',y_test[:5])
    print('pred:  ',pred[:5])

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
degree: 1
Scores: [ 0.9682832   0.96882629  0.96765279  0.97283368]
Mean squared error: 0.01
Variance score: 0.97
y_test: [ 2.85508529  2.94973971  2.75635373  1.96371667  3.3201863 ]
pred:   [ 2.89633672  2.93799101  2.7411413   2.07556002  3.22769496]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
degree: 2
Scores: [ 0.96752401  0.96364198  0.9633273   0.96972415]
Mean squared error: 0.01
Variance score: 0.97
y_test: [ 2.85508529  2.94973971  2.75635373  1.96371667  3.3201863 ]
pred:   [ 2.90235429  2.93821114  2.73435303  2.08723873  3.22719309]
------------------------------------------------------------------------------------------

In [216]:
import numpy as np
import time
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import learning_curve
from sklearn.kernel_ridge import KernelRidge
import matplotlib.pyplot as plt

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import RidgeCV 
from sklearn.metrics import mean_squared_error, r2_score

# Random sample of the data for the Test is kept
X_train, X_test, y_train, y_test = train_test_split(
    data, label, test_size=0.25, random_state=2)


kr = GridSearchCV(KernelRidge(kernel='rbf'), cv=5,
                  param_grid={"alpha": [1e0, 0.1, 1e-2, 1e-3],
                              "gamma": np.logspace(-2, 2, 5)})

t0 = time.time()
kr.fit(X_train, y_train)
kr_fit = time.time() - t0
print("KRR complexity and bandwidth selected and model fitted in %.3f s"
      % kr_fit)


pred = kr.predict(X_test)
# The mean squared error
print("Mean squared error: %.2f"
          % mean_squared_error(y_test, pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.4f' % r2_score(y_test, pred))
print('Sample y_test:',y_test[:5])
print('Sample pred:  ',pred[:5])

KRR complexity and bandwidth selected and model fitted in 1.021 s
Mean squared error: 0.01
Variance score: 0.9724
Sample y_test: [ 3.44333169  1.55023629  3.43498205  2.17696001  2.83458413]
Sample pred:   [ 3.3780122   1.4180844   3.58964151  2.18511231  2.86856006]
