In [2]:
import csv
PID=[]
IData=[]
ILabel=[]
TEmbarked=[]

with open('data/train.csv', 'r') as csvfile:
    data = csv.DictReader(csvfile, delimiter=',')
    for row in data:
        if row['Age']=='':
            row['Age']='0'
        PID.append(int(row['PassengerId']))
        IData.append([int(row['Pclass'])
                      ,row['Sex'],float(row['Age']),int(row['SibSp']),int(row['Parch'])])
        TEmbarked.append(row['Embarked'])
        ILabel.append(row['Survived'])
#print(IData)
#print(len(IData))
#print(len(ILabel))

In [3]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#values_TEmbarked = array(TEmbarked)
values_TEmbarked = array(TEmbarked)
print('-'*100)
print('Hot encoding TEmbarked attribute')
print('-'*100)
print('-'*100)
print(values_TEmbarked[:10])
# integer encode
label_encoder = LabelEncoder()
integer_encoded_TEmbarked = label_encoder.fit_transform(values_TEmbarked)
print(integer_encoded_TEmbarked[:10])
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)

#chaging the shape to a single column from row
integer_encoded_TEmbarked = integer_encoded_TEmbarked.reshape(len(integer_encoded_TEmbarked), 1)

onehot_encoded_TEmbarked = onehot_encoder.fit_transform(integer_encoded_TEmbarked)
print(onehot_encoded_TEmbarked[:10])
#inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
#print(inverted)
print('-'*100)


values_ILabel = array(ILabel)
print('-'*100)
print('Hot encoding ILabel attribute')
print('-'*100)
print('-'*100)
print(values_ILabel[:10])
# integer encode
label_encoder = LabelEncoder()
integer_encoded_values_ILabel = label_encoder.fit_transform(values_ILabel)
print(integer_encoded_values_ILabel[:10])
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)

#chaging the shape to a single column from row
integer_encoded_values_ILabel = integer_encoded_values_ILabel.reshape(len(integer_encoded_values_ILabel), 1)

onehot_encoded_ILabel= onehot_encoder.fit_transform(integer_encoded_values_ILabel)
print(onehot_encoded_ILabel[:10])
#inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
#print(inverted)
print('-'*100)



----------------------------------------------------------------------------------------------------
Hot encoding TEmbarked attribute
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
['S' 'C' 'S' 'S' 'S' 'Q' 'S' 'S' 'S' 'C']
[3 1 3 3 3 2 3 3 3 1]
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Hot encoding ILabel attribute
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
['0' '1' '1' '1

In [4]:
for datum in IData:
    if datum[1]=='male':
        datum[1]=0
    if datum[1]=='female':
        datum[1]=1        
#     if datum[5]=='S':
#         datum[5]=0
#     if datum[5]=='C':
#         datum[5]=1
#     if datum[5]=='Q':
#         datum[5]=2
#     if datum[5]=='':
#         datum[5]=4
       
# for datum in IData:
#     for i in range(0,6):
#         if not isinstance(datum[i], (int,float)):
#             print(type(datum[i]),datum[i],datum,i)
print(IData)
print(onehot_encoded_ILabel[:10])

[[3, 0, 22.0, 1, 0], [1, 1, 38.0, 1, 0], [3, 1, 26.0, 0, 0], [1, 1, 35.0, 1, 0], [3, 0, 35.0, 0, 0], [3, 0, 0.0, 0, 0], [1, 0, 54.0, 0, 0], [3, 0, 2.0, 3, 1], [3, 1, 27.0, 0, 2], [2, 1, 14.0, 1, 0], [3, 1, 4.0, 1, 1], [1, 1, 58.0, 0, 0], [3, 0, 20.0, 0, 0], [3, 0, 39.0, 1, 5], [3, 1, 14.0, 0, 0], [2, 1, 55.0, 0, 0], [3, 0, 2.0, 4, 1], [2, 0, 0.0, 0, 0], [3, 1, 31.0, 1, 0], [3, 1, 0.0, 0, 0], [2, 0, 35.0, 0, 0], [2, 0, 34.0, 0, 0], [3, 1, 15.0, 0, 0], [1, 0, 28.0, 0, 0], [3, 1, 8.0, 3, 1], [3, 1, 38.0, 1, 5], [3, 0, 0.0, 0, 0], [1, 0, 19.0, 3, 2], [3, 1, 0.0, 0, 0], [3, 0, 0.0, 0, 0], [1, 0, 40.0, 0, 0], [1, 1, 0.0, 1, 0], [3, 1, 0.0, 0, 0], [2, 0, 66.0, 0, 0], [1, 0, 28.0, 1, 0], [1, 0, 42.0, 1, 0], [3, 0, 0.0, 0, 0], [3, 0, 21.0, 0, 0], [3, 1, 18.0, 2, 0], [3, 1, 14.0, 1, 0], [3, 1, 40.0, 1, 0], [2, 1, 27.0, 1, 0], [3, 0, 0.0, 0, 0], [2, 1, 3.0, 1, 2], [3, 1, 19.0, 0, 0], [3, 0, 0.0, 0, 0], [3, 0, 0.0, 1, 0], [3, 1, 0.0, 0, 0], [3, 0, 0.0, 2, 0], [3, 1, 18.0, 1, 0], [3, 0, 7.0, 4, 1],

In [5]:
IData=np.array(IData)
IData = np.concatenate((IData, onehot_encoded_TEmbarked), axis=1)
IData.shape

(891, 9)

In [10]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.python import keras
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Flatten, Conv2D, Dropout

# a=pd.read_csv("../input/digit-recognizer/train.csv")
# a.drop('label', axis=1)

# img_rows, img_cols = 28, 28
# num_classes = 10

# def data_prep(raw):
#     out_y = keras.utils.to_categorical(raw.label, num_classes)

#     num_images = raw.shape[0]
#     x_as_array = raw.values[:,1:]
#     x_shaped_array = x_as_array.reshape(num_images, img_rows, img_cols, 1)
#     out_x = x_shaped_array / 255
#     return out_x, out_y

train_size = 891
#train_file = "../input/digit-recognizer/train.csv"
#raw_data = pd.read_csv(train_file)

#x, y = data_prep(raw_data)
x=IData
y=ILabel

model = Sequential()
model.add(Conv2D(20, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(1, 9, 1)))
model.add(Conv2D(20, kernel_size=(3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer='adam',
              metrics=['accuracy'])
model.fit(x, y,
          batch_size=128,
          epochs=2,
          validation_split = 0.2)

ImportError: cannot import name 'keras'

In [139]:
import tensorflow as tf

X=tf.placeholder(tf.float32,[None,9])
W=tf.Variable(tf.zeros([9,10]))
b=tf.Variable(tf.zeros([10]))

#h=tf.matmul(X,W)+b
h=tf.nn.softmax(tf.matmul(X,W)+b)

W2=tf.Variable(tf.zeros([10,2]))
b2=tf.Variable(tf.zeros([2]))

Ylogits = tf.matmul(h,W2)+b2
Y=tf.nn.softmax(Ylogits)

init = tf.global_variables_initializer()


Y_ = tf.placeholder(tf.float32,[None,2])
cross_entropy= -tf.reduce_sum(Y_*tf.log(Y + 1e-4))

loss = tf.losses.softmax_cross_entropy(onehot_labels=Y_, logits=Ylogits)


is_correct=tf.equal(tf.argmax(Y,1),tf.argmax(Y_,1))
accuracy=tf.reduce_mean(tf.cast(is_correct,tf.float32))

optimizer = tf.train.GradientDescentOptimizer(0.003)
train_step=optimizer.minimize(loss)
learning_rate = 0.003
#train_step = tf.train.AdamOptimizer(learning_rate).minimize(cross_entropy)

sess=tf.Session()
sess.run(init)

for i in range(20):
    #batch_X,batch_Y=mnist.train.next_batch(100)
    train_data={X:IData,Y_:onehot_encoded_ILabel}
    #print(train_data)
    
    sess.run(train_step,feed_dict=train_data)
    
    a,c=sess.run([accuracy,cross_entropy],feed_dict=train_data)
    print(str(i) + "Train: accuracy:" + str(a) + " loss: " + str(c))
    
    #test_data={X:mnist.test.images,Y_:mnist.test.labels}
    #a,c=sess.run([accuracy,cross_entropy],feed_dict=test_data)
    #print(str(i) + " : accuracy:" + str(a) + " loss: " + str(c))
    
    print("b is:")
    print (sess.run(b))
    
    #print("W is:")
    #print (sess.run(W))
    

0Train: accuracy:0.61616164 loss: 617.3368
b is:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1Train: accuracy:0.61616164 loss: 617.2582
b is:
[-6.6186943e-16 -6.6186943e-16 -6.6186943e-16 -6.6186943e-16
 -6.6186943e-16 -6.6186943e-16 -6.6186943e-16 -6.6186943e-16
  2.4268633e-15  2.4268633e-15]
2Train: accuracy:0.61616164 loss: 617.1804
b is:
[-3.3093471e-15 -3.3093471e-15 -3.3093471e-15 -3.3093471e-15
 -3.3093471e-15 -3.3093471e-15 -3.3093471e-15 -3.3093471e-15
  1.0964074e-14  1.0964074e-14]
3Train: accuracy:0.61616164 loss: 617.1016
b is:
[-4.9208637e-15 -4.9208637e-15 -4.9208637e-15 -4.9208637e-15
 -4.9208637e-15 -4.9208637e-15 -4.9208637e-15 -4.9208637e-15
  1.2441296e-14  1.2441296e-14]
4Train: accuracy:0.61616164 loss: 617.0231
b is:
[-4.9208637e-15 -4.9208637e-15 -4.9208637e-15 -4.9208637e-15
 -4.9208637e-15 -4.9208637e-15 -4.9208637e-15 -4.9208637e-15
  9.7938185e-15  9.7938185e-15]
5Train: accuracy:0.61616164 loss: 616.94324
b is:
[-5.4963976e-15 -5.4963976e-15 -5.4963976e-15 -5.4963976e

In [ ]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    IData, ILabel, test_size=0.2)

#print(IData)  
from sklearn import svm
clf = svm.SVC(kernel='linear',C=10,probability=True)
clf.fit(X_train, y_train)

print("Accuracy:",clf.score(X_test, y_test))
Y_predict=clf.predict(X_test)
print(y_test[:10])
print(Y_predict[:10])

In [51]:
from sklearn.model_selection import cross_val_score
clf2 = svm.SVC(kernel='linear', degree=3,C=10)
scores = cross_val_score(clf2, IData, ILabel, cv=5)
print(scores)

[0.80446927 0.80446927 0.78651685 0.75280899 0.78531073]


In [14]:
import csv
TPID=[]
TIData=[]
with open('data/test.csv', 'r') as csvfile:
    data = csv.DictReader(csvfile, delimiter=',')
    for row in data:
        if row['Age']=='':
            row['Age']='0'
        TPID.append(int(row['PassengerId']))
        TIData.append([int(row['Pclass'])
                      ,row['Sex'],float(row['Age']),int(row['SibSp']),int(row['Parch']),row['Embarked']])

In [8]:
for datum in TIData:
    if datum[1]=='male':
        datum[1]=0
    if datum[1]=='female':
        datum[1]=1        
    if datum[5]=='S':
        datum[5]=0
    if datum[5]=='C':
        datum[5]=1
    if datum[5]=='Q':
        datum[5]=2
    if datum[5]=='':
        datum[5]=4

In [9]:
print(type(TIData))
import numpy as np
TIData = np.array(TIData)
print(type(TIData))

<class 'list'>
<class 'numpy.ndarray'>


In [139]:
print(TIData)

[[ 3.   0.  34.5  0.   0.   2. ]
 [ 3.   1.  47.   1.   0.   0. ]
 [ 2.   0.  62.   0.   0.   2. ]
 ...
 [ 3.   0.  38.5  0.   0.   0. ]
 [ 3.   0.   0.   0.   0.   0. ]
 [ 3.   0.   0.   1.   1.   1. ]]


In [10]:
TY_predict=clf.predict(TIData)

In [11]:
print(TY_predict[:10])


['0' '0' '1' '0' '1' '0' '0' '0' '0' '0']


In [15]:
TY_predict=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0]
import csv

with open('data/gender_submission.csv', 'w') as csvfile:
    fieldnames = ['PassengerId', 'Survived']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    count=0
    for idx in TPID:
        writer.writerow({'PassengerId': idx, 'Survived':TY_predict[count]})
        count=count+1